import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
export default function sobre(){
    return (
        <>
          <Head>
            <title>Conquista</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
    
          </Head>
          <main>
            <Header />
            <div>Baner quem somos</div>
            <section>
              <div>Missao</div>
              <div>Visao</div>
              <div>Valores</div>
            </section>
            <Footer/>
          </main>
        </>
      );
}